#site-setting
url : "https://manumanu97.github.io"
github_repository: https://github.com/ManuManu97
theme: jekyll-theme-hacker
title: ManuManu97's page
description: Manu's official page for my projects, review and etc.
name: &name "Manu"
show_downloads: false

#github page setting
github:
  is_project_page: false

#site-author
name : *name 
bio  : "Nothing to say"

#footer
footer_left: Esdrongo
footer_right: ...

collections:
  projects:
    output: true
  ctf:
    output: true
  notes:
    output: true
#plugin
plugins:
  - jekyll-sitemap
  - jekyll-feed
